name: flutter_super
description: Reactive state management framework for scalable flutter applications.
version: 1.4.0
repository: https://github.com/DrDejaVuNG/super
issue_tracker: https://github.com/DrDejaVuNG/super/issues
# homepage: https://drdejavu.ng
# documentation: https://super.drdejavu.ng

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_super: ^1.4.1
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  super_test: ^1.1.0

  very_good_analysis: ^5.0.0+1

screenshots:
  - description: Super Logo.
    path: screenshots/logo.png

topics:
  - state
  - widgets
  - reactive
